### ISSUE TITLE
LDAP sync command fails on ValueError

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/RCAMP#271]
The `syncldapusers` command is failing with the following traceback:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/rcamp/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/opt/rcamp/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/rcamp/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/rcamp/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/srv/uwsgi/RCAMP/rcamp/accounts/management/commands/syncldapusers.py", line 41, in handle
    auth_users_remaining.remove(auth_user.username)
ValueError: list.remove(x): x not in list
```

**Comment by zebulasampedro** [comment]
This error is the result of a user from an unrecognized OU. When the `effective_uid` property on an LDAP user is queried, it calls `lib.ldap_utils.get_suffixed_username()` in the background, which evaluates the appropriate suffix as `None` if the specified organization is not configured in settings (https://github.com/ResearchComputing/RCAMP/blob/master/rcamp/lib/ldap_utils.py#L23).

A safe fix _for now_ would be simply configuring the OU in settings, as user-facing elements would not be affected.
