### ISSUE TITLE
Import error breaking signal

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/RCAMP#324]
```
Internal Server Error: /accounts/account-request/create/intent
Traceback (most recent call last):
  File "/opt/rcamp/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rcamp/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rcamp/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/rcamp/lib/python2.7/site-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./accounts/views.py", line 111, in form_valid
    account_request_approved.send(sender=account_request.__class__,account_request=account_request)
  File "/opt/rcamp/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "./projects/receivers.py", line 22, in check_general_eligibility
    except Intent.DoesNotExist:
NameError: global name 'Intent' is not defined
```

**Comment by zebulasampedro** [comment]
Duplicate of #303
