### ISSUE TITLE
API missing static file

### ISSUE THREAD

**Issue by AaronTHolt** [ResearchComputing/RCAMP#404]
TemplateDoesNotExist: django_filters/rest_framework/crispy_form.html
Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/lib/python2.7/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/lib/python2.7/site-packages/rest_framework/renderers.py", line 733, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/lib/python2.7/site-packages/rest_framework/renderers.py", line 710, in get_context
    'filter_form': self.get_filter_form(data, view, request),
  File "/usr/lib/python2.7/site-packages/rest_framework/renderers.py", line 642, in get_filter_form
    html = backend().to_html(request, queryset, view)
  File "/usr/lib/python2.7/site-packages/django_filters/rest_framework/backends.py", line 61, in to_html
    template = loader.get_template(self.template)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: django_filters/rest_framework/crispy_form.html

**Comment by AaronTHolt** [comment]
django-crispy-forms 1.5.2 isn't compatible with Django 1.11. Should update to django-crispy-forms 1.8.1.
